services:
  - type: web
    name: discord-camera-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TARGET_CHANNEL_ID
        sync: false
      - key: ANNOUNCE_CHANNEL_ID
        sync: false
